[platformio]
src_dir = src
lib_dir = lib
include_dir = include

[env:atmega8]
platform = atmelavr
board = ATmega8
board_build.mcu = atmega8
board_build.f_cpu = 8000000L
upload_protocol = usbasp
build_flags = -Os
monitor_speed = 9600
